# Generated by Django 4.0.3 on 2022-03-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Book',
        ),
    ]
