# Generated by Django 4.0.3 on 2022-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchbooks', '0002_book_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_published',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings_1_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings_2_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings_3_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings_4_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings_5_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings_counts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='review_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
