# Generated by Django 4.0.3 on 2022-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchbooks', '0003_book_author_link_book_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_counts',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
    ]
