# Generated by Django 4.0.3 on 2022-04-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchbooks', '0004_alter_book_date_published_alter_book_ratings_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_counts',
            field=models.IntegerField(null=True),
        ),
    ]
