# Generated by Django 4.0.3 on 2022-04-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchbooks', '0005_alter_book_average_rating_alter_book_ratings_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
